version: '3'
services: 
  
  cockroachdb-0:
    container_name: cockroachdb-0
    hostname: cockroachdb-0
    image: cockroachdb/cockroach:v22.2.8
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start --insecure --join=cockroachdb-0,cockroachdb-1
    networks: 
      - roachnet
    volumes: 
      - ./cockroach-data-0:/cockroach/cockroach-data
  cockroachdb-1:
    container_name: cockroachdb-1
    hostname: cockroachdb-1
    image: cockroachdb/cockroach:v22.2.8
    command: start --insecure --join=cocckroachdb-0,cockroachdb-1
    networks:
      - roachnet
    volumes: 
      - ./cockroach-data-1:/cockroach/cockroach-data 
  company_service:
    build: 
      context: ./company
      dockerfile: Dockerfile
    image: company
    ports:
      - "3001:3001"
    restart: always
    networks:
        - roachnet
    depends_on:
        - cockroachdb-0  
  employee_service:
    build: 
      context: ./employee
      dockerfile: Dockerfile
    image : employee
    ports:
        - "3002:3002"
    restart: always 
    networks:
        - roachnet
    depends_on:
        - cockroachdb-0
    
networks:
  roachnet:
    driver: bridge